name: flutter_ddd
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  dartz: ^0.10.1
  freezed_annotation: ^1.1.0
  flutter_bloc: ^7.3.3
  firebase_core: ^1.10.6
  firebase_auth: ^3.3.4
  google_sign_in: ^5.2.1
  get_it: ^7.2.0
  injectable: ^1.5.0
  provider: ^6.0.1
  uuid: ^3.0.5
  auto_route: ^2.4.0
  kt_dart: ^0.10.0
  json_annotation: ^4.4.0
  cloud_firestore: ^3.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner:
  freezed: ^1.1.0
  lint: ^1.7.2
  injectable_generator: ^1.5.2
  auto_route_generator: ^2.4.0
  json_serializable: ^6.1.3


# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
